name: Milestone16$(Rev:.r)

trigger:
  branches:
    include:
     - release/*
     - develop
  paths:
    exclude:
    - 'docs/*'


variables:
 - group: Tokens
 - name: major
   value: 15

 - name: minor
   value: $[counter(variables['major'], 200)]



stages:

#Merge to Develop, Deploy Alpha builds
- stage: Alpha
  condition: eq(variables['build.sourceBranch'], 'refs/heads/develop')
  dependsOn: []
  jobs:

  - template: build_templates/deciderjob.yml

  - job: BuildCLI
    dependsOn: InstallNodeModules
    displayName: sfdx-plugin
    condition:   succeeded('InstallNodeModules')
    pool:
      vmImage: 'ubuntu-latest'
    steps:
             - template: build_templates/buildcli.yml
               parameters:
                commitToGit: true
                bump: 'prerelease'
                version: 'alpha'
                publish: true


  - deployment: BuildAzPipelines
    displayName: azpipelines
    dependsOn: InstallNodeModules
    condition:  succeeded('InstallNodeModules')
    timeoutInMinutes: 20
    pool:
      vmImage: 'ubuntu-latest'
    environment: alpha
    strategy:
       runOnce:
         deploy:
           steps:

             - template: build_templates/buildazpipelines.yml
               parameters:
                commitToGit: true
                bump: 'prerelease'
                stageToDeploy: 'alpha'
                version: 'alpha'
                environmentToDeploy: 'alpha'
                toBuild: true
                organization: dxatscalereview
                buildNumber: $(minor)


#Beta Stage
- stage: Beta
  condition: and(succeeded('Alpha'),eq(variables['build.sourceBranch'], 'refs/heads/develop'))
  dependsOn: Alpha
  jobs:

  - template: build_templates/deciderjob.yml

  - job: BuildCLI
    displayName: sfdx-plugin
    dependsOn: InstallNodeModules
    condition:   succeeded('InstallNodeModules')
    pool:
      vmImage: 'ubuntu-latest'
    steps:
             - template: build_templates/buildcli.yml
               parameters:
                commitToGit: false
                bump: 'prerelease'
                version: 'beta'
                publish: false


  - deployment: BuildAzPipelines
    displayName: azpipelines
    dependsOn: InstallNodeModules
    condition:  succeeded('InstallNodeModules')
    timeoutInMinutes: 20
    pool:
      vmImage: 'ubuntu-latest'
    environment: beta
    strategy:
       runOnce:
         deploy:
           steps:

             - template: build_templates/buildazpipelines.yml
               parameters:
                commitToGit: false
                bump: 'prerelease'
                stageToDeploy: 'beta'
                version: 'beta'
                environmentToDeploy: 'beta'
                toBuild: true
                organization: dxatscalereview
                buildNumber: $(minor)

#Prod Stage
- stage: Prod
  condition: and(succeeded('Beta'),eq(variables['build.sourceBranch'], 'refs/heads/develop'))
  dependsOn: Beta
  jobs:

  - template: build_templates/deciderjob.yml

  - job: BuildCLI
    displayName: sfdx-plugin
    dependsOn: InstallNodeModules
    condition:   succeeded('InstallNodeModules')
    pool:
      vmImage: 'ubuntu-latest'
    steps:
             - template: build_templates/buildcli.yml
               parameters:
                commitToGit: false
                bump: 'patch'
                version: 'latest'
                publish: false


  - deployment: BuildAzPipelines
    displayName: azpipelines
    dependsOn: BuildCLI
    condition:  succeeded('InstallNodeModules')
    timeoutInMinutes: 30
    pool:
      vmImage: 'ubuntu-latest'
    environment: prod
    strategy:
       runOnce:
         deploy:
           steps:

             - template: build_templates/buildazpipelines.yml
               parameters:
                commitToGit: false
                bump: 'patch'
                stageToDeploy: 'prod'
                version: 'prod'
                environmentToDeploy: 'prod'
                toBuild: true
                organization: dxatscalereview
                buildNumber: $(minor)
